2020-08-13 00:22:44.410 [error] <0.580.0> CRASH REPORT Process <0.580.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:22:44.410 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.134983772.519307265.14940> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.580.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:22:47.157 [error] <0.849.0> CRASH REPORT Process <0.849.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:22:47.157 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.134983772.519307265.14940> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.849.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:22:49.818 [error] <0.854.0> CRASH REPORT Process <0.854.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:22:49.818 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.134983772.519307265.14940> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.854.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:22:52.145 [error] <0.855.0> CRASH REPORT Process <0.855.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:22:52.145 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.134983772.519307265.14940> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.855.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:22:54.520 [error] <0.856.0> CRASH REPORT Process <0.856.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:22:54.520 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.134983772.519307265.14940> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.856.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:22:56.909 [error] <0.857.0> CRASH REPORT Process <0.857.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:22:56.910 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.134983772.519307265.14940> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.857.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:22:59.238 [error] <0.858.0> CRASH REPORT Process <0.858.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:22:59.238 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.134983772.519307265.14940> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.858.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:23:01.592 [error] <0.859.0> CRASH REPORT Process <0.859.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:23:01.593 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.134983772.519307265.14940> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.859.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:23:04.159 [error] <0.860.0> CRASH REPORT Process <0.860.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:23:04.160 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.134983772.519307265.14940> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.860.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:23:06.601 [error] <0.861.0> CRASH REPORT Process <0.861.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:23:06.603 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.134983772.519307265.14940> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.861.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:23:09.015 [error] <0.862.0> CRASH REPORT Process <0.862.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:23:09.015 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.134983772.519307265.14940> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.862.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:23:11.366 [error] <0.863.0> CRASH REPORT Process <0.863.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:23:11.366 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.134983772.519307265.14940> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.863.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:23:13.719 [error] <0.864.0> CRASH REPORT Process <0.864.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:23:13.719 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.134983772.519307265.14940> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.864.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:23:16.070 [error] <0.865.0> CRASH REPORT Process <0.865.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:23:16.072 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.134983772.519307265.14940> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.865.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:23:18.404 [error] <0.866.0> CRASH REPORT Process <0.866.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:23:18.405 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.134983772.519307265.14940> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.866.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:23:20.800 [error] <0.867.0> CRASH REPORT Process <0.867.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:23:20.800 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.134983772.519307265.14940> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.867.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:23:23.131 [error] <0.868.0> CRASH REPORT Process <0.868.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:23:23.131 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.134983772.519307265.14940> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.868.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:23:25.444 [error] <0.869.0> CRASH REPORT Process <0.869.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:23:25.444 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.134983772.519307265.14940> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.869.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:23:27.751 [error] <0.870.0> CRASH REPORT Process <0.870.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:23:27.751 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.134983772.519307265.14940> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.870.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:23:30.090 [error] <0.871.0> CRASH REPORT Process <0.871.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:23:30.091 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.134983772.519307265.14940> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.871.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:23:32.458 [error] <0.872.0> CRASH REPORT Process <0.872.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:23:32.458 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.134983772.519307265.14940> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.872.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:23:34.777 [error] <0.873.0> CRASH REPORT Process <0.873.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:23:34.777 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.134983772.519307265.14940> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.873.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:23:37.078 [error] <0.874.0> CRASH REPORT Process <0.874.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:23:37.078 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.134983772.519307265.14940> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.874.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:23:39.392 [error] <0.875.0> CRASH REPORT Process <0.875.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:23:39.395 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.134983772.519307265.14940> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.875.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:23:43.516 [error] <0.876.0> CRASH REPORT Process <0.876.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:23:43.516 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.134983772.519307265.14940> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.876.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:23:45.836 [error] <0.877.0> CRASH REPORT Process <0.877.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:23:45.836 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.134983772.519307265.14940> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.877.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:23:48.181 [error] <0.878.0> CRASH REPORT Process <0.878.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:23:48.181 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.134983772.519307265.14940> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.878.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:23:50.590 [error] <0.879.0> CRASH REPORT Process <0.879.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:23:50.590 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.134983772.519307265.14940> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.879.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:23:52.893 [error] <0.880.0> CRASH REPORT Process <0.880.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:23:52.893 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.134983772.519307265.14940> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.880.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:23:55.272 [error] <0.881.0> CRASH REPORT Process <0.881.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:23:55.272 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.134983772.519307265.14940> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.881.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:23:57.575 [error] <0.882.0> CRASH REPORT Process <0.882.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:23:57.575 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.134983772.519307265.14940> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.882.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:23:59.879 [error] <0.883.0> CRASH REPORT Process <0.883.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:23:59.879 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.134983772.519307265.14940> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.883.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:24:02.283 [error] <0.884.0> CRASH REPORT Process <0.884.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:24:02.284 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.134983772.519307265.14940> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.884.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:24:04.615 [error] <0.885.0> CRASH REPORT Process <0.885.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:24:04.615 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.134983772.519307265.14940> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.885.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:24:06.925 [error] <0.886.0> CRASH REPORT Process <0.886.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:24:06.925 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.134983772.519307265.14940> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.886.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:24:09.283 [error] <0.887.0> CRASH REPORT Process <0.887.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:24:09.284 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.134983772.519307265.14940> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.887.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:24:11.604 [error] <0.888.0> CRASH REPORT Process <0.888.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:24:11.604 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.134983772.519307265.14940> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.888.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:24:14.042 [error] <0.889.0> CRASH REPORT Process <0.889.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:24:14.042 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.134983772.519307265.14940> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.889.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:24:16.367 [error] <0.890.0> CRASH REPORT Process <0.890.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:24:16.367 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.134983772.519307265.14940> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.890.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:24:18.683 [error] <0.891.0> CRASH REPORT Process <0.891.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:24:18.684 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.134983772.519307265.14940> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.891.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:24:21.049 [error] <0.892.0> CRASH REPORT Process <0.892.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:24:21.049 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.134983772.519307265.14940> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.892.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:24:23.342 [error] <0.893.0> CRASH REPORT Process <0.893.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:24:23.342 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.134983772.519307265.14940> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.893.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:26:02.094 [error] <0.580.0> CRASH REPORT Process <0.580.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:26:02.094 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.166990432.3740008451.240394> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.580.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:26:04.473 [error] <0.854.0> CRASH REPORT Process <0.854.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:26:04.473 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.166990432.3740008451.240394> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.854.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:29:46.036 [error] <0.580.0> CRASH REPORT Process <0.580.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:29:46.037 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.2534029094.3740794881.123769> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.580.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:29:48.368 [error] <0.849.0> CRASH REPORT Process <0.849.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:29:48.368 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.2534029094.3740794881.123769> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.849.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:29:50.670 [error] <0.850.0> CRASH REPORT Process <0.850.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:29:50.670 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.2534029094.3740794881.123769> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.850.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:29:52.993 [error] <0.851.0> CRASH REPORT Process <0.851.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:29:52.993 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.2534029094.3740794881.123769> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.851.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:29:56.323 [error] <0.852.0> CRASH REPORT Process <0.852.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:29:56.323 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.2534029094.3740794881.123769> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.852.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:29:58.861 [error] <0.853.0> CRASH REPORT Process <0.853.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:29:58.862 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.2534029094.3740794881.123769> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.853.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:30:02.664 [error] <0.857.0> CRASH REPORT Process <0.857.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:30:02.665 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.2534029094.3740794881.123769> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.857.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:30:04.979 [error] <0.864.0> CRASH REPORT Process <0.864.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:30:04.980 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.2534029094.3740794881.123769> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.864.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:30:07.283 [error] <0.865.0> CRASH REPORT Process <0.865.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:30:07.284 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.2534029094.3740794881.123769> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.865.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:30:09.617 [error] <0.866.0> CRASH REPORT Process <0.866.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:30:09.617 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.2534029094.3740794881.123769> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.866.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:30:11.963 [error] <0.867.0> CRASH REPORT Process <0.867.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:30:11.975 [error] <0.455.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.2534029094.3740794881.123769> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.867.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:30:23.535 [error] <0.570.0> CRASH REPORT Process <0.570.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:30:23.536 [error] <0.445.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.1489486449.788529154.119384> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.570.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:30:25.897 [error] <0.842.0> CRASH REPORT Process <0.842.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:30:25.897 [error] <0.445.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.1489486449.788529154.119384> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.842.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:30:28.218 [error] <0.843.0> CRASH REPORT Process <0.843.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:30:28.218 [error] <0.445.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.1489486449.788529154.119384> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.843.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:30:30.523 [error] <0.844.0> CRASH REPORT Process <0.844.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:30:30.523 [error] <0.445.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.1489486449.788529154.119384> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.844.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:34:58.874 [error] <0.570.0> CRASH REPORT Process <0.570.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:34:58.874 [error] <0.445.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.388117818.1058013185.184087> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.570.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:35:02.364 [error] <0.841.0> CRASH REPORT Process <0.841.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:35:02.364 [error] <0.445.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.388117818.1058013185.184087> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.841.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:35:05.807 [error] <0.842.0> CRASH REPORT Process <0.842.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:35:05.807 [error] <0.445.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.388117818.1058013185.184087> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.842.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:35:09.088 [error] <0.843.0> CRASH REPORT Process <0.843.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:35:09.088 [error] <0.445.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.388117818.1058013185.184087> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.843.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:35:12.321 [error] <0.844.0> CRASH REPORT Process <0.844.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:35:12.321 [error] <0.445.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.388117818.1058013185.184087> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.844.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:37:28.724 [error] <0.570.0> CRASH REPORT Process <0.570.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:37:28.724 [error] <0.445.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.1308676475.2937061377.95687> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.570.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:45:59.433 [error] <0.570.0> CRASH REPORT Process <0.570.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:45:59.434 [error] <0.445.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.3515569155.2669936641.131262> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.570.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 00:46:02.820 [error] <0.837.0> CRASH REPORT Process <0.837.0> with 0 neighbours exited with reason: watcher_command_error in 'Elixir.Phoenix.Endpoint.Watcher':watch/3 line 37
2020-08-13 00:46:02.820 [error] <0.445.0> Supervisor 'Elixir.PuzzlespaceWeb.Endpoint' had child #Ref<0.3515569155.2669936641.131262> started with 'Elixir.Phoenix.Endpoint.Watcher':start_link({node,[<<"node_modules/webpack/bin/webpack.js">>,<<"--mode">>,<<"development">>,<<"--watch-stdin">>],...}) at <0.837.0> exit with reason watcher_command_error in context child_terminated
2020-08-13 02:16:06.321 [error] <0.929.0> CRASH REPORT Process <0.929.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Ecto.Query.CastError',message => <<"deps/ecto/lib/ecto/repo/queryable.ex:418: value `{:ok, %Puzzlespace.User{__meta__: #Ecto.Schema.Metadata<:loaded, \"users\">, auth_tokens: #Ecto.Association.NotLoaded<association :auth_tokens is not loaded>, entity_id: \"55e18438-e69f-4e10-a2df-bdd9dc0aadd6\", hashed_pass: \"$pbkdf2-sha512$160000$MIJbvhY4dDDfEdwurSR.mw$4juBq4nf9ejXRh4u0zEmdclRE4aFtiYOP0jkXNBJLGnMtmLHOgPQLF3LB2vlAqed1v5xQ0fJ8VVQfAABnTAoOA\"...">>,...},...},...},...},...}
2020-08-13 02:16:06.511 [error] <0.929.0> Cowboy stream 3 with ranch listener 'Elixir.PuzzlespaceWeb.Endpoint.HTTP' and connection process <0.919.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Ecto.Query.CastError',message => <<"deps/ecto/lib/ecto/repo/queryable.ex:418: value `{:ok, %Puzzlespace.User{__meta__: #Ecto.Schema.Metadata<:loaded, \"users\">, auth_tokens: #Ecto.Association.NotLoaded<association :auth_tokens is not loaded>, entity_id: \"55e18438-e69f-4e10-a2df-bdd9dc0aadd6\", hashed_pass: \"$pbkdf2-sha512$160000$MIJbvhY4dDDfEdwurSR.mw$4juBq4nf9ejXRh4u0zEmdclRE4aFtiYOP0jkXNBJLGnMtmLHOgPQLF3LB2vlAqed1v5xQ0fJ8VVQfAABnTAoOA\", ...">>,...},...},...},...}
2020-08-13 02:17:59.621 [error] <0.977.0> CRASH REPORT Process <0.977.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.ActionClauseError',args => [#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 134,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"en-US,en;q=0.5">>,<<"connection">> => <<"keep-a...">>,...},...}},...},...],...},...},...},...},...}
2020-08-13 02:17:59.627 [error] <0.977.0> Cowboy stream 5 with ranch listener 'Elixir.PuzzlespaceWeb.Endpoint.HTTP' and connection process <0.941.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.ActionClauseError',args => [#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 134,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"en-US,en;q=0.5">>,<<"connection">> => <<"keep-ali...">>,...},...}},...},...],...},...},...},...}
2020-08-13 08:07:53.541 [error] <0.604.0> gen_server <0.604.0> terminated with reason: socket_closed_unexpectedly
2020-08-13 08:07:53.541 [error] <0.604.0> CRASH REPORT Process <0.604.0> with 0 neighbours exited with reason: socket_closed_unexpectedly in gen_server:handle_common_reply/8 line 751
2020-08-13 08:07:53.546 [error] <0.602.0> Supervisor {<0.602.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.603.0>, {amqp_params_network,<<"psserver">>,{plaintext,<<"fizzbuzz">>},<<"/">>,"192.168.1.142",5672,0,0,...}) at <0.604.0> exit with reason socket_closed_unexpectedly in context child_terminated
2020-08-13 08:07:53.546 [error] <0.602.0> Supervisor {<0.602.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.603.0>, {amqp_params_network,<<"psserver">>,{plaintext,<<"fizzbuzz">>},<<"/">>,"192.168.1.142",5672,0,0,...}) at <0.604.0> exit with reason reached_max_restart_intensity in context shutdown
2020-08-13 21:33:57.830 [error] <0.941.0> CRASH REPORT Process <0.941.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => whereis,kind => nil,module => 'Elixir.GenServer'},[{'Elixir.GenServer',whereis,[<<"P4/gEGDI4sasxQvwqw8wSxg9+I0=">>],[{file,"lib/gen_server.ex"},{line,1195}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1011}]},{'Elixir.Puzzlespace.SessionHandler',get_authenticated_user,2,[{file,"lib/puzzlespace/authentication/session_handler.ex"},{line,6}]},{'Elixir.PuzzlespaceWeb.PuzzleSocket',...},...]},...},...},...}
2020-08-13 21:33:57.849 [error] <0.941.0> Cowboy stream 1 with ranch listener 'Elixir.PuzzlespaceWeb.Endpoint.HTTP' and connection process <0.940.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => whereis,kind => nil,module => 'Elixir.GenServer'},[{'Elixir.GenServer',whereis,[<<"P4/gEGDI4sasxQvwqw8wSxg9+I0=">>],[{file,"lib/gen_server.ex"},{line,1195}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1011}]},{'Elixir.Puzzlespace.SessionHandler',get_authenticated_user,2,[{file,"lib/puzzlespace/authentication/session_handler.ex"},{line,6}]},{'Elixir.PuzzlespaceWeb.PuzzleSocket',...},...]},...},...}
2020-08-13 21:33:58.256 [error] <0.949.0> CRASH REPORT Process <0.949.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => whereis,kind => nil,module => 'Elixir.GenServer'},[{'Elixir.GenServer',whereis,[<<"P4/gEGDI4sasxQvwqw8wSxg9+I0=">>],[{file,"lib/gen_server.ex"},{line,1195}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1011}]},{'Elixir.Puzzlespace.SessionHandler',get_authenticated_user,2,[{file,"lib/puzzlespace/authentication/session_handler.ex"},{line,6}]},{'Elixir.PuzzlespaceWeb.PuzzleSocket',...},...]},...},...},...}
2020-08-13 21:33:58.257 [error] <0.949.0> Cowboy stream 1 with ranch listener 'Elixir.PuzzlespaceWeb.Endpoint.HTTP' and connection process <0.948.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => whereis,kind => nil,module => 'Elixir.GenServer'},[{'Elixir.GenServer',whereis,[<<"P4/gEGDI4sasxQvwqw8wSxg9+I0=">>],[{file,"lib/gen_server.ex"},{line,1195}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1011}]},{'Elixir.Puzzlespace.SessionHandler',get_authenticated_user,2,[{file,"lib/puzzlespace/authentication/session_handler.ex"},{line,6}]},{'Elixir.PuzzlespaceWeb.PuzzleSocket',...},...]},...},...}
2020-08-13 21:33:58.595 [error] <0.952.0> CRASH REPORT Process <0.952.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => whereis,kind => nil,module => 'Elixir.GenServer'},[{'Elixir.GenServer',whereis,[<<"P4/gEGDI4sasxQvwqw8wSxg9+I0=">>],[{file,"lib/gen_server.ex"},{line,1195}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1011}]},{'Elixir.Puzzlespace.SessionHandler',get_authenticated_user,2,[{file,"lib/puzzlespace/authentication/session_handler.ex"},{line,6}]},{'Elixir.PuzzlespaceWeb.PuzzleSocket',...},...]},...},...},...}
2020-08-13 21:33:58.595 [error] <0.952.0> Cowboy stream 1 with ranch listener 'Elixir.PuzzlespaceWeb.Endpoint.HTTP' and connection process <0.951.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => whereis,kind => nil,module => 'Elixir.GenServer'},[{'Elixir.GenServer',whereis,[<<"P4/gEGDI4sasxQvwqw8wSxg9+I0=">>],[{file,"lib/gen_server.ex"},{line,1195}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1011}]},{'Elixir.Puzzlespace.SessionHandler',get_authenticated_user,2,[{file,"lib/puzzlespace/authentication/session_handler.ex"},{line,6}]},{'Elixir.PuzzlespaceWeb.PuzzleSocket',...},...]},...},...}
2020-08-13 21:33:59.083 [error] <0.955.0> CRASH REPORT Process <0.955.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => whereis,kind => nil,module => 'Elixir.GenServer'},[{'Elixir.GenServer',whereis,[<<"P4/gEGDI4sasxQvwqw8wSxg9+I0=">>],[{file,"lib/gen_server.ex"},{line,1195}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1011}]},{'Elixir.Puzzlespace.SessionHandler',get_authenticated_user,2,[{file,"lib/puzzlespace/authentication/session_handler.ex"},{line,6}]},{'Elixir.PuzzlespaceWeb.PuzzleSocket',...},...]},...},...},...}
2020-08-13 21:33:59.083 [error] <0.955.0> Cowboy stream 1 with ranch listener 'Elixir.PuzzlespaceWeb.Endpoint.HTTP' and connection process <0.954.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => whereis,kind => nil,module => 'Elixir.GenServer'},[{'Elixir.GenServer',whereis,[<<"P4/gEGDI4sasxQvwqw8wSxg9+I0=">>],[{file,"lib/gen_server.ex"},{line,1195}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1011}]},{'Elixir.Puzzlespace.SessionHandler',get_authenticated_user,2,[{file,"lib/puzzlespace/authentication/session_handler.ex"},{line,6}]},{'Elixir.PuzzlespaceWeb.PuzzleSocket',...},...]},...},...}
2020-08-13 21:33:59.796 [error] <0.958.0> CRASH REPORT Process <0.958.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => whereis,kind => nil,module => 'Elixir.GenServer'},[{'Elixir.GenServer',whereis,[<<"P4/gEGDI4sasxQvwqw8wSxg9+I0=">>],[{file,"lib/gen_server.ex"},{line,1195}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1011}]},{'Elixir.Puzzlespace.SessionHandler',get_authenticated_user,2,[{file,"lib/puzzlespace/authentication/session_handler.ex"},{line,6}]},{'Elixir.PuzzlespaceWeb.PuzzleSocket',...},...]},...},...},...}
2020-08-13 21:33:59.797 [error] <0.958.0> Cowboy stream 1 with ranch listener 'Elixir.PuzzlespaceWeb.Endpoint.HTTP' and connection process <0.957.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => whereis,kind => nil,module => 'Elixir.GenServer'},[{'Elixir.GenServer',whereis,[<<"P4/gEGDI4sasxQvwqw8wSxg9+I0=">>],[{file,"lib/gen_server.ex"},{line,1195}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1011}]},{'Elixir.Puzzlespace.SessionHandler',get_authenticated_user,2,[{file,"lib/puzzlespace/authentication/session_handler.ex"},{line,6}]},{'Elixir.PuzzlespaceWeb.PuzzleSocket',...},...]},...},...}
2020-08-13 21:34:00.856 [error] <0.961.0> CRASH REPORT Process <0.961.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => whereis,kind => nil,module => 'Elixir.GenServer'},[{'Elixir.GenServer',whereis,[<<"P4/gEGDI4sasxQvwqw8wSxg9+I0=">>],[{file,"lib/gen_server.ex"},{line,1195}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1011}]},{'Elixir.Puzzlespace.SessionHandler',get_authenticated_user,2,[{file,"lib/puzzlespace/authentication/session_handler.ex"},{line,6}]},{'Elixir.PuzzlespaceWeb.PuzzleSocket',...},...]},...},...},...}
2020-08-13 21:34:00.856 [error] <0.961.0> Cowboy stream 1 with ranch listener 'Elixir.PuzzlespaceWeb.Endpoint.HTTP' and connection process <0.960.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => whereis,kind => nil,module => 'Elixir.GenServer'},[{'Elixir.GenServer',whereis,[<<"P4/gEGDI4sasxQvwqw8wSxg9+I0=">>],[{file,"lib/gen_server.ex"},{line,1195}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1011}]},{'Elixir.Puzzlespace.SessionHandler',get_authenticated_user,2,[{file,"lib/puzzlespace/authentication/session_handler.ex"},{line,6}]},{'Elixir.PuzzlespaceWeb.PuzzleSocket',...},...]},...},...}
2020-08-13 21:34:02.420 [error] <0.964.0> CRASH REPORT Process <0.964.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => whereis,kind => nil,module => 'Elixir.GenServer'},[{'Elixir.GenServer',whereis,[<<"P4/gEGDI4sasxQvwqw8wSxg9+I0=">>],[{file,"lib/gen_server.ex"},{line,1195}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1011}]},{'Elixir.Puzzlespace.SessionHandler',get_authenticated_user,2,[{file,"lib/puzzlespace/authentication/session_handler.ex"},{line,6}]},{'Elixir.PuzzlespaceWeb.PuzzleSocket',...},...]},...},...},...}
2020-08-13 21:34:02.421 [error] <0.964.0> Cowboy stream 1 with ranch listener 'Elixir.PuzzlespaceWeb.Endpoint.HTTP' and connection process <0.963.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => whereis,kind => nil,module => 'Elixir.GenServer'},[{'Elixir.GenServer',whereis,[<<"P4/gEGDI4sasxQvwqw8wSxg9+I0=">>],[{file,"lib/gen_server.ex"},{line,1195}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1011}]},{'Elixir.Puzzlespace.SessionHandler',get_authenticated_user,2,[{file,"lib/puzzlespace/authentication/session_handler.ex"},{line,6}]},{'Elixir.PuzzlespaceWeb.PuzzleSocket',...},...]},...},...}
2020-08-13 21:34:04.751 [error] <0.967.0> CRASH REPORT Process <0.967.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => whereis,kind => nil,module => 'Elixir.GenServer'},[{'Elixir.GenServer',whereis,[<<"P4/gEGDI4sasxQvwqw8wSxg9+I0=">>],[{file,"lib/gen_server.ex"},{line,1195}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1011}]},{'Elixir.Puzzlespace.SessionHandler',get_authenticated_user,2,[{file,"lib/puzzlespace/authentication/session_handler.ex"},{line,6}]},{'Elixir.PuzzlespaceWeb.PuzzleSocket',...},...]},...},...},...}
2020-08-13 21:34:04.752 [error] <0.967.0> Cowboy stream 1 with ranch listener 'Elixir.PuzzlespaceWeb.Endpoint.HTTP' and connection process <0.966.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => whereis,kind => nil,module => 'Elixir.GenServer'},[{'Elixir.GenServer',whereis,[<<"P4/gEGDI4sasxQvwqw8wSxg9+I0=">>],[{file,"lib/gen_server.ex"},{line,1195}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1011}]},{'Elixir.Puzzlespace.SessionHandler',get_authenticated_user,2,[{file,"lib/puzzlespace/authentication/session_handler.ex"},{line,6}]},{'Elixir.PuzzlespaceWeb.PuzzleSocket',...},...]},...},...}
2020-08-13 21:34:08.228 [error] <0.970.0> CRASH REPORT Process <0.970.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => whereis,kind => nil,module => 'Elixir.GenServer'},[{'Elixir.GenServer',whereis,[<<"P4/gEGDI4sasxQvwqw8wSxg9+I0=">>],[{file,"lib/gen_server.ex"},{line,1195}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1011}]},{'Elixir.Puzzlespace.SessionHandler',get_authenticated_user,2,[{file,"lib/puzzlespace/authentication/session_handler.ex"},{line,6}]},{'Elixir.PuzzlespaceWeb.PuzzleSocket',...},...]},...},...},...}
2020-08-13 21:34:08.229 [error] <0.970.0> Cowboy stream 1 with ranch listener 'Elixir.PuzzlespaceWeb.Endpoint.HTTP' and connection process <0.969.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => whereis,kind => nil,module => 'Elixir.GenServer'},[{'Elixir.GenServer',whereis,[<<"P4/gEGDI4sasxQvwqw8wSxg9+I0=">>],[{file,"lib/gen_server.ex"},{line,1195}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1011}]},{'Elixir.Puzzlespace.SessionHandler',get_authenticated_user,2,[{file,"lib/puzzlespace/authentication/session_handler.ex"},{line,6}]},{'Elixir.PuzzlespaceWeb.PuzzleSocket',...},...]},...},...}
2020-08-13 21:34:11.796 [error] <0.972.0> CRASH REPORT Process <0.972.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => move_desc_to_tuple,kind => nil,module => 'Elixir.STPuzzleCoordinator'},[{'Elixir.STPuzzleCoordinator',move_desc_to_tuple,[#{<<"buttons">> => [<<"K">>,<<"SHIFT">>],<<"numpad">> => false}],[{file,"lib/puzzlespace/puzzles/stpuzzle/s_t_puzzle_coordinator.ex"},{line,86}]},{'Elixir.Enum','-map/2-lists^map/1-0-',2,[{file,"lib/enum.ex"},{line,1396}]},{'Elixir.STPuzzleCoordinator',...},...]},...},...},...}
2020-08-13 21:34:11.800 [error] <0.972.0> Cowboy stream 20 with ranch listener 'Elixir.PuzzlespaceWeb.Endpoint.HTTP' and connection process <0.863.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => move_desc_to_tuple,kind => nil,module => 'Elixir.STPuzzleCoordinator'},[{'Elixir.STPuzzleCoordinator',move_desc_to_tuple,[#{<<"buttons">> => [<<"K">>,<<"SHIFT">>],<<"numpad">> => false}],[{file,"lib/puzzlespace/puzzles/stpuzzle/s_t_puzzle_coordinator.ex"},{line,86}]},{'Elixir.Enum','-map/2-lists^map/1-0-',2,[{file,"lib/enum.ex"},{line,1396}]},{'Elixir.STPuzzleCoordinator',...},...]},...},...}
2020-08-13 21:34:13.430 [error] <0.975.0> CRASH REPORT Process <0.975.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => whereis,kind => nil,module => 'Elixir.GenServer'},[{'Elixir.GenServer',whereis,[<<"P4/gEGDI4sasxQvwqw8wSxg9+I0=">>],[{file,"lib/gen_server.ex"},{line,1195}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1011}]},{'Elixir.Puzzlespace.SessionHandler',get_authenticated_user,2,[{file,"lib/puzzlespace/authentication/session_handler.ex"},{line,6}]},{'Elixir.PuzzlespaceWeb.PuzzleSocket',...},...]},...},...},...}
2020-08-13 21:34:13.432 [error] <0.975.0> Cowboy stream 1 with ranch listener 'Elixir.PuzzlespaceWeb.Endpoint.HTTP' and connection process <0.974.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => whereis,kind => nil,module => 'Elixir.GenServer'},[{'Elixir.GenServer',whereis,[<<"P4/gEGDI4sasxQvwqw8wSxg9+I0=">>],[{file,"lib/gen_server.ex"},{line,1195}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1011}]},{'Elixir.Puzzlespace.SessionHandler',get_authenticated_user,2,[{file,"lib/puzzlespace/authentication/session_handler.ex"},{line,6}]},{'Elixir.PuzzlespaceWeb.PuzzleSocket',...},...]},...},...}
2020-08-13 21:34:21.224 [error] <0.978.0> CRASH REPORT Process <0.978.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => whereis,kind => nil,module => 'Elixir.GenServer'},[{'Elixir.GenServer',whereis,[<<"P4/gEGDI4sasxQvwqw8wSxg9+I0=">>],[{file,"lib/gen_server.ex"},{line,1195}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1011}]},{'Elixir.Puzzlespace.SessionHandler',get_authenticated_user,2,[{file,"lib/puzzlespace/authentication/session_handler.ex"},{line,6}]},{'Elixir.PuzzlespaceWeb.PuzzleSocket',...},...]},...},...},...}
2020-08-13 21:34:21.224 [error] <0.978.0> Cowboy stream 1 with ranch listener 'Elixir.PuzzlespaceWeb.Endpoint.HTTP' and connection process <0.977.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => whereis,kind => nil,module => 'Elixir.GenServer'},[{'Elixir.GenServer',whereis,[<<"P4/gEGDI4sasxQvwqw8wSxg9+I0=">>],[{file,"lib/gen_server.ex"},{line,1195}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1011}]},{'Elixir.Puzzlespace.SessionHandler',get_authenticated_user,2,[{file,"lib/puzzlespace/authentication/session_handler.ex"},{line,6}]},{'Elixir.PuzzlespaceWeb.PuzzleSocket',...},...]},...},...}
2020-08-13 21:34:32.893 [error] <0.981.0> CRASH REPORT Process <0.981.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => whereis,kind => nil,module => 'Elixir.GenServer'},[{'Elixir.GenServer',whereis,[<<"P4/gEGDI4sasxQvwqw8wSxg9+I0=">>],[{file,"lib/gen_server.ex"},{line,1195}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1011}]},{'Elixir.Puzzlespace.SessionHandler',get_authenticated_user,2,[{file,"lib/puzzlespace/authentication/session_handler.ex"},{line,6}]},{'Elixir.PuzzlespaceWeb.PuzzleSocket',...},...]},...},...},...}
2020-08-13 21:34:32.893 [error] <0.981.0> Cowboy stream 1 with ranch listener 'Elixir.PuzzlespaceWeb.Endpoint.HTTP' and connection process <0.980.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => whereis,kind => nil,module => 'Elixir.GenServer'},[{'Elixir.GenServer',whereis,[<<"P4/gEGDI4sasxQvwqw8wSxg9+I0=">>],[{file,"lib/gen_server.ex"},{line,1195}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1011}]},{'Elixir.Puzzlespace.SessionHandler',get_authenticated_user,2,[{file,"lib/puzzlespace/authentication/session_handler.ex"},{line,6}]},{'Elixir.PuzzlespaceWeb.PuzzleSocket',...},...]},...},...}
2020-08-13 22:21:01.742 [error] <0.619.0> CRASH REPORT Process <0.619.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => whereis,kind => nil,module => 'Elixir.GenServer'},[{'Elixir.GenServer',whereis,[<<"P4/gEGDI4sasxQvwqw8wSxg9+I0=">>],[{file,"lib/gen_server.ex"},{line,1195}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1011}]},{'Elixir.Puzzlespace.SessionHandler',get_authenticated_user,2,[{file,"lib/puzzlespace/authentication/session_handler.ex"},{line,6}]},{'Elixir.PuzzlespaceWeb.PuzzleSocket',...},...]},...},...},...}
2020-08-13 22:21:01.776 [error] <0.619.0> Cowboy stream 1 with ranch listener 'Elixir.PuzzlespaceWeb.Endpoint.HTTP' and connection process <0.618.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => whereis,kind => nil,module => 'Elixir.GenServer'},[{'Elixir.GenServer',whereis,[<<"P4/gEGDI4sasxQvwqw8wSxg9+I0=">>],[{file,"lib/gen_server.ex"},{line,1195}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1011}]},{'Elixir.Puzzlespace.SessionHandler',get_authenticated_user,2,[{file,"lib/puzzlespace/authentication/session_handler.ex"},{line,6}]},{'Elixir.PuzzlespaceWeb.PuzzleSocket',...},...]},...},...}
2020-08-13 22:25:29.483 [error] <0.1111.0> CRASH REPORT Process <0.1111.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => whereis,kind => nil,module => 'Elixir.GenServer'},[{'Elixir.GenServer',whereis,[<<"P4/gEGDI4sasxQvwqw8wSxg9+I0=">>],[{file,"lib/gen_server.ex"},{line,1195}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1011}]},{'Elixir.Puzzlespace.SessionHandler',get_authenticated_user,2,[{file,"lib/puzzlespace/authentication/session_handler.ex"},{line,6}]},{'Elixir.PuzzlespaceWeb.PuzzleSocket',...},...]},...},...},...}
2020-08-13 22:25:29.516 [error] <0.1111.0> Cowboy stream 1 with ranch listener 'Elixir.PuzzlespaceWeb.Endpoint.HTTP' and connection process <0.1110.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => whereis,kind => nil,module => 'Elixir.GenServer'},[{'Elixir.GenServer',whereis,[<<"P4/gEGDI4sasxQvwqw8wSxg9+I0=">>],[{file,"lib/gen_server.ex"},{line,1195}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1011}]},{'Elixir.Puzzlespace.SessionHandler',get_authenticated_user,2,[{file,"lib/puzzlespace/authentication/session_handler.ex"},{line,6}]},{'Elixir.PuzzlespaceWeb.PuzzleSocket',...},...]},...},...}
2020-08-13 22:25:30.054 [error] <0.1118.0> CRASH REPORT Process <0.1118.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => whereis,kind => nil,module => 'Elixir.GenServer'},[{'Elixir.GenServer',whereis,[<<"P4/gEGDI4sasxQvwqw8wSxg9+I0=">>],[{file,"lib/gen_server.ex"},{line,1195}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1011}]},{'Elixir.Puzzlespace.SessionHandler',get_authenticated_user,2,[{file,"lib/puzzlespace/authentication/session_handler.ex"},{line,6}]},{'Elixir.PuzzlespaceWeb.PuzzleSocket',...},...]},...},...},...}
2020-08-13 22:25:30.054 [error] <0.1118.0> Cowboy stream 1 with ranch listener 'Elixir.PuzzlespaceWeb.Endpoint.HTTP' and connection process <0.1117.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => whereis,kind => nil,module => 'Elixir.GenServer'},[{'Elixir.GenServer',whereis,[<<"P4/gEGDI4sasxQvwqw8wSxg9+I0=">>],[{file,"lib/gen_server.ex"},{line,1195}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1011}]},{'Elixir.Puzzlespace.SessionHandler',get_authenticated_user,2,[{file,"lib/puzzlespace/authentication/session_handler.ex"},{line,6}]},{'Elixir.PuzzlespaceWeb.PuzzleSocket',...},...]},...},...}
2020-08-13 22:25:30.459 [error] <0.1121.0> CRASH REPORT Process <0.1121.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => whereis,kind => nil,module => 'Elixir.GenServer'},[{'Elixir.GenServer',whereis,[<<"P4/gEGDI4sasxQvwqw8wSxg9+I0=">>],[{file,"lib/gen_server.ex"},{line,1195}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1011}]},{'Elixir.Puzzlespace.SessionHandler',get_authenticated_user,2,[{file,"lib/puzzlespace/authentication/session_handler.ex"},{line,6}]},{'Elixir.PuzzlespaceWeb.PuzzleSocket',...},...]},...},...},...}
2020-08-13 22:25:30.460 [error] <0.1121.0> Cowboy stream 1 with ranch listener 'Elixir.PuzzlespaceWeb.Endpoint.HTTP' and connection process <0.1120.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => whereis,kind => nil,module => 'Elixir.GenServer'},[{'Elixir.GenServer',whereis,[<<"P4/gEGDI4sasxQvwqw8wSxg9+I0=">>],[{file,"lib/gen_server.ex"},{line,1195}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1011}]},{'Elixir.Puzzlespace.SessionHandler',get_authenticated_user,2,[{file,"lib/puzzlespace/authentication/session_handler.ex"},{line,6}]},{'Elixir.PuzzlespaceWeb.PuzzleSocket',...},...]},...},...}
2020-08-13 22:25:31.049 [error] <0.1124.0> CRASH REPORT Process <0.1124.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => whereis,kind => nil,module => 'Elixir.GenServer'},[{'Elixir.GenServer',whereis,[<<"P4/gEGDI4sasxQvwqw8wSxg9+I0=">>],[{file,"lib/gen_server.ex"},{line,1195}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1011}]},{'Elixir.Puzzlespace.SessionHandler',get_authenticated_user,2,[{file,"lib/puzzlespace/authentication/session_handler.ex"},{line,6}]},{'Elixir.PuzzlespaceWeb.PuzzleSocket',...},...]},...},...},...}
2020-08-13 22:25:31.050 [error] <0.1124.0> Cowboy stream 1 with ranch listener 'Elixir.PuzzlespaceWeb.Endpoint.HTTP' and connection process <0.1123.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => whereis,kind => nil,module => 'Elixir.GenServer'},[{'Elixir.GenServer',whereis,[<<"P4/gEGDI4sasxQvwqw8wSxg9+I0=">>],[{file,"lib/gen_server.ex"},{line,1195}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1011}]},{'Elixir.Puzzlespace.SessionHandler',get_authenticated_user,2,[{file,"lib/puzzlespace/authentication/session_handler.ex"},{line,6}]},{'Elixir.PuzzlespaceWeb.PuzzleSocket',...},...]},...},...}
2020-08-13 22:25:31.917 [error] <0.1127.0> CRASH REPORT Process <0.1127.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => whereis,kind => nil,module => 'Elixir.GenServer'},[{'Elixir.GenServer',whereis,[<<"P4/gEGDI4sasxQvwqw8wSxg9+I0=">>],[{file,"lib/gen_server.ex"},{line,1195}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1011}]},{'Elixir.Puzzlespace.SessionHandler',get_authenticated_user,2,[{file,"lib/puzzlespace/authentication/session_handler.ex"},{line,6}]},{'Elixir.PuzzlespaceWeb.PuzzleSocket',...},...]},...},...},...}
2020-08-13 22:25:31.917 [error] <0.1127.0> Cowboy stream 1 with ranch listener 'Elixir.PuzzlespaceWeb.Endpoint.HTTP' and connection process <0.1126.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => whereis,kind => nil,module => 'Elixir.GenServer'},[{'Elixir.GenServer',whereis,[<<"P4/gEGDI4sasxQvwqw8wSxg9+I0=">>],[{file,"lib/gen_server.ex"},{line,1195}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1011}]},{'Elixir.Puzzlespace.SessionHandler',get_authenticated_user,2,[{file,"lib/puzzlespace/authentication/session_handler.ex"},{line,6}]},{'Elixir.PuzzlespaceWeb.PuzzleSocket',...},...]},...},...}
2020-08-13 22:25:33.218 [error] <0.1130.0> CRASH REPORT Process <0.1130.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => whereis,kind => nil,module => 'Elixir.GenServer'},[{'Elixir.GenServer',whereis,[<<"P4/gEGDI4sasxQvwqw8wSxg9+I0=">>],[{file,"lib/gen_server.ex"},{line,1195}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1011}]},{'Elixir.Puzzlespace.SessionHandler',get_authenticated_user,2,[{file,"lib/puzzlespace/authentication/session_handler.ex"},{line,6}]},{'Elixir.PuzzlespaceWeb.PuzzleSocket',...},...]},...},...},...}
2020-08-13 22:25:33.218 [error] <0.1130.0> Cowboy stream 1 with ranch listener 'Elixir.PuzzlespaceWeb.Endpoint.HTTP' and connection process <0.1129.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => whereis,kind => nil,module => 'Elixir.GenServer'},[{'Elixir.GenServer',whereis,[<<"P4/gEGDI4sasxQvwqw8wSxg9+I0=">>],[{file,"lib/gen_server.ex"},{line,1195}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1011}]},{'Elixir.Puzzlespace.SessionHandler',get_authenticated_user,2,[{file,"lib/puzzlespace/authentication/session_handler.ex"},{line,6}]},{'Elixir.PuzzlespaceWeb.PuzzleSocket',...},...]},...},...}
2020-08-13 22:25:34.057 [error] <0.1132.0> CRASH REPORT Process <0.1132.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => move_desc_to_tuple,kind => nil,module => 'Elixir.STPuzzleCoordinator'},[{'Elixir.STPuzzleCoordinator',move_desc_to_tuple,[#{<<"buttons">> => [<<"c">>],<<"numpad">> => false}],[{file,"lib/puzzlespace/puzzles/stpuzzle/s_t_puzzle_coordinator.ex"},{line,86}]},{'Elixir.Enum','-map/2-lists^map/1-0-',2,[{file,"lib/enum.ex"},{line,1396}]},{'Elixir.STPuzzleCoordinator',update,...},...]},...},...},...}
2020-08-13 22:25:34.059 [error] <0.1132.0> Cowboy stream 6 with ranch listener 'Elixir.PuzzlespaceWeb.Endpoint.HTTP' and connection process <0.1089.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => move_desc_to_tuple,kind => nil,module => 'Elixir.STPuzzleCoordinator'},[{'Elixir.STPuzzleCoordinator',move_desc_to_tuple,[#{<<"buttons">> => [<<"c">>],<<"numpad">> => false}],[{file,"lib/puzzlespace/puzzles/stpuzzle/s_t_puzzle_coordinator.ex"},{line,86}]},{'Elixir.Enum','-map/2-lists^map/1-0-',2,[{file,"lib/enum.ex"},{line,1396}]},{'Elixir.STPuzzleCoordinator',update,...},...]},...},...}
2020-08-13 22:25:34.274 [error] <0.1134.0> CRASH REPORT Process <0.1134.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => move_desc_to_tuple,kind => nil,module => 'Elixir.STPuzzleCoordinator'},[{'Elixir.STPuzzleCoordinator',move_desc_to_tuple,[#{<<"buttons">> => [<<"c">>],<<"numpad">> => false}],[{file,"lib/puzzlespace/puzzles/stpuzzle/s_t_puzzle_coordinator.ex"},{line,86}]},{'Elixir.Enum','-map/2-lists^map/1-0-',2,[{file,"lib/enum.ex"},{line,1396}]},{'Elixir.STPuzzleCoordinator',update,...},...]},...},...},...}
2020-08-13 22:25:34.275 [error] <0.1134.0> Cowboy stream 7 with ranch listener 'Elixir.PuzzlespaceWeb.Endpoint.HTTP' and connection process <0.1089.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => move_desc_to_tuple,kind => nil,module => 'Elixir.STPuzzleCoordinator'},[{'Elixir.STPuzzleCoordinator',move_desc_to_tuple,[#{<<"buttons">> => [<<"c">>],<<"numpad">> => false}],[{file,"lib/puzzlespace/puzzles/stpuzzle/s_t_puzzle_coordinator.ex"},{line,86}]},{'Elixir.Enum','-map/2-lists^map/1-0-',2,[{file,"lib/enum.ex"},{line,1396}]},{'Elixir.STPuzzleCoordinator',update,...},...]},...},...}
2020-08-13 22:25:35.126 [error] <0.1137.0> CRASH REPORT Process <0.1137.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => whereis,kind => nil,module => 'Elixir.GenServer'},[{'Elixir.GenServer',whereis,[<<"P4/gEGDI4sasxQvwqw8wSxg9+I0=">>],[{file,"lib/gen_server.ex"},{line,1195}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1011}]},{'Elixir.Puzzlespace.SessionHandler',get_authenticated_user,2,[{file,"lib/puzzlespace/authentication/session_handler.ex"},{line,6}]},{'Elixir.PuzzlespaceWeb.PuzzleSocket',...},...]},...},...},...}
2020-08-13 22:25:35.127 [error] <0.1137.0> Cowboy stream 1 with ranch listener 'Elixir.PuzzlespaceWeb.Endpoint.HTTP' and connection process <0.1136.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => whereis,kind => nil,module => 'Elixir.GenServer'},[{'Elixir.GenServer',whereis,[<<"P4/gEGDI4sasxQvwqw8wSxg9+I0=">>],[{file,"lib/gen_server.ex"},{line,1195}]},{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,1011}]},{'Elixir.Puzzlespace.SessionHandler',get_authenticated_user,2,[{file,"lib/puzzlespace/authentication/session_handler.ex"},{line,6}]},{'Elixir.PuzzlespaceWeb.PuzzleSocket',...},...]},...},...}
2020-08-13 22:37:21.191 [error] <0.871.0> CRASH REPORT Process <0.871.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[{ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Puzzlespace.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.Puzzlespace.User',auth_tokens => #{'__cardinality__' => many,'__field__' => auth_tokens,'__owner__' => 'Elixir.Puzzlespace.User','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},...}},...],...},...]},...},...},...}
2020-08-13 22:37:21.199 [error] <0.871.0> Cowboy stream 1 with ranch listener 'Elixir.PuzzlespaceWeb.Endpoint.HTTP' and connection process <0.869.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[{ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Puzzlespace.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.Puzzlespace.User',auth_tokens => #{'__cardinality__' => many,'__field__' => auth_tokens,'__owner__' => 'Elixir.Puzzlespace.User','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},...}},...],...},...]},...},...}
2020-08-13 22:37:26.540 [error] <0.903.0> CRASH REPORT Process <0.903.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[{ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Puzzlespace.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.Puzzlespace.User',auth_tokens => #{'__cardinality__' => many,'__field__' => auth_tokens,'__owner__' => 'Elixir.Puzzlespace.User','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},...}},...],...},...]},...},...},...}
2020-08-13 22:37:26.542 [error] <0.903.0> Cowboy stream 1 with ranch listener 'Elixir.PuzzlespaceWeb.Endpoint.HTTP' and connection process <0.902.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[{ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Puzzlespace.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.Puzzlespace.User',auth_tokens => #{'__cardinality__' => many,'__field__' => auth_tokens,'__owner__' => 'Elixir.Puzzlespace.User','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},...}},...],...},...]},...},...}
2020-08-13 22:37:26.968 [error] <0.911.0> CRASH REPORT Process <0.911.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[{ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Puzzlespace.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.Puzzlespace.User',auth_tokens => #{'__cardinality__' => many,'__field__' => auth_tokens,'__owner__' => 'Elixir.Puzzlespace.User','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},...}},...],...},...]},...},...},...}
2020-08-13 22:37:26.972 [error] <0.911.0> Cowboy stream 1 with ranch listener 'Elixir.PuzzlespaceWeb.Endpoint.HTTP' and connection process <0.910.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[{ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Puzzlespace.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.Puzzlespace.User',auth_tokens => #{'__cardinality__' => many,'__field__' => auth_tokens,'__owner__' => 'Elixir.Puzzlespace.User','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},...}},...],...},...]},...},...}
2020-08-13 22:37:27.284 [error] <0.914.0> CRASH REPORT Process <0.914.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[{ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Puzzlespace.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.Puzzlespace.User',auth_tokens => #{'__cardinality__' => many,'__field__' => auth_tokens,'__owner__' => 'Elixir.Puzzlespace.User','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},...}},...],...},...]},...},...},...}
2020-08-13 22:37:27.285 [error] <0.914.0> Cowboy stream 1 with ranch listener 'Elixir.PuzzlespaceWeb.Endpoint.HTTP' and connection process <0.913.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[{ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Puzzlespace.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.Puzzlespace.User',auth_tokens => #{'__cardinality__' => many,'__field__' => auth_tokens,'__owner__' => 'Elixir.Puzzlespace.User','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},...}},...],...},...]},...},...}
2020-08-13 22:37:27.710 [error] <0.917.0> CRASH REPORT Process <0.917.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[{ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Puzzlespace.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.Puzzlespace.User',auth_tokens => #{'__cardinality__' => many,'__field__' => auth_tokens,'__owner__' => 'Elixir.Puzzlespace.User','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},...}},...],...},...]},...},...},...}
2020-08-13 22:37:27.711 [error] <0.917.0> Cowboy stream 1 with ranch listener 'Elixir.PuzzlespaceWeb.Endpoint.HTTP' and connection process <0.916.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[{ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Puzzlespace.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.Puzzlespace.User',auth_tokens => #{'__cardinality__' => many,'__field__' => auth_tokens,'__owner__' => 'Elixir.Puzzlespace.User','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},...}},...],...},...]},...},...}
2020-08-13 22:37:28.314 [error] <0.920.0> CRASH REPORT Process <0.920.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[{ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Puzzlespace.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.Puzzlespace.User',auth_tokens => #{'__cardinality__' => many,'__field__' => auth_tokens,'__owner__' => 'Elixir.Puzzlespace.User','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},...}},...],...},...]},...},...},...}
2020-08-13 22:37:28.314 [error] <0.920.0> Cowboy stream 1 with ranch listener 'Elixir.PuzzlespaceWeb.Endpoint.HTTP' and connection process <0.919.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[{ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Puzzlespace.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.Puzzlespace.User',auth_tokens => #{'__cardinality__' => many,'__field__' => auth_tokens,'__owner__' => 'Elixir.Puzzlespace.User','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},...}},...],...},...]},...},...}
2020-08-13 22:37:29.202 [error] <0.923.0> CRASH REPORT Process <0.923.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[{ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Puzzlespace.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.Puzzlespace.User',auth_tokens => #{'__cardinality__' => many,'__field__' => auth_tokens,'__owner__' => 'Elixir.Puzzlespace.User','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},...}},...],...},...]},...},...},...}
2020-08-13 22:37:29.202 [error] <0.923.0> Cowboy stream 1 with ranch listener 'Elixir.PuzzlespaceWeb.Endpoint.HTTP' and connection process <0.922.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[{ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Puzzlespace.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.Puzzlespace.User',auth_tokens => #{'__cardinality__' => many,'__field__' => auth_tokens,'__owner__' => 'Elixir.Puzzlespace.User','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},...}},...],...},...]},...},...}
2020-08-13 22:37:30.513 [error] <0.926.0> CRASH REPORT Process <0.926.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[{ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Puzzlespace.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.Puzzlespace.User',auth_tokens => #{'__cardinality__' => many,'__field__' => auth_tokens,'__owner__' => 'Elixir.Puzzlespace.User','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},...}},...],...},...]},...},...},...}
2020-08-13 22:37:30.514 [error] <0.926.0> Cowboy stream 1 with ranch listener 'Elixir.PuzzlespaceWeb.Endpoint.HTTP' and connection process <0.925.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[{ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Puzzlespace.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.Puzzlespace.User',auth_tokens => #{'__cardinality__' => many,'__field__' => auth_tokens,'__owner__' => 'Elixir.Puzzlespace.User','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},...}},...],...},...]},...},...}
2020-08-13 22:37:32.455 [error] <0.929.0> CRASH REPORT Process <0.929.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[{ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Puzzlespace.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.Puzzlespace.User',auth_tokens => #{'__cardinality__' => many,'__field__' => auth_tokens,'__owner__' => 'Elixir.Puzzlespace.User','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},...}},...],...},...]},...},...},...}
2020-08-13 22:37:32.456 [error] <0.929.0> Cowboy stream 1 with ranch listener 'Elixir.PuzzlespaceWeb.Endpoint.HTTP' and connection process <0.928.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[{ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Puzzlespace.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.Puzzlespace.User',auth_tokens => #{'__cardinality__' => many,'__field__' => auth_tokens,'__owner__' => 'Elixir.Puzzlespace.User','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},...}},...],...},...]},...},...}
2020-08-13 22:37:35.345 [error] <0.932.0> CRASH REPORT Process <0.932.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[{ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Puzzlespace.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.Puzzlespace.User',auth_tokens => #{'__cardinality__' => many,'__field__' => auth_tokens,'__owner__' => 'Elixir.Puzzlespace.User','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},...}},...],...},...]},...},...},...}
2020-08-13 22:37:35.347 [error] <0.932.0> Cowboy stream 1 with ranch listener 'Elixir.PuzzlespaceWeb.Endpoint.HTTP' and connection process <0.931.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[{ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Puzzlespace.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.Puzzlespace.User',auth_tokens => #{'__cardinality__' => many,'__field__' => auth_tokens,'__owner__' => 'Elixir.Puzzlespace.User','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},...}},...],...},...]},...},...}
2020-08-13 22:37:39.657 [error] <0.935.0> CRASH REPORT Process <0.935.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[{ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Puzzlespace.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.Puzzlespace.User',auth_tokens => #{'__cardinality__' => many,'__field__' => auth_tokens,'__owner__' => 'Elixir.Puzzlespace.User','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},...}},...],...},...]},...},...},...}
2020-08-13 22:37:39.659 [error] <0.935.0> Cowboy stream 1 with ranch listener 'Elixir.PuzzlespaceWeb.Endpoint.HTTP' and connection process <0.934.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[{ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Puzzlespace.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.Puzzlespace.User',auth_tokens => #{'__cardinality__' => many,'__field__' => auth_tokens,'__owner__' => 'Elixir.Puzzlespace.User','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},...}},...],...},...]},...},...}
2020-08-13 22:37:46.094 [error] <0.938.0> CRASH REPORT Process <0.938.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[{ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Puzzlespace.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.Puzzlespace.User',auth_tokens => #{'__cardinality__' => many,'__field__' => auth_tokens,'__owner__' => 'Elixir.Puzzlespace.User','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},...}},...],...},...]},...},...},...}
2020-08-13 22:37:46.095 [error] <0.938.0> Cowboy stream 1 with ranch listener 'Elixir.PuzzlespaceWeb.Endpoint.HTTP' and connection process <0.937.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[{ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Puzzlespace.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.Puzzlespace.User',auth_tokens => #{'__cardinality__' => many,'__field__' => auth_tokens,'__owner__' => 'Elixir.Puzzlespace.User','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},...}},...],...},...]},...},...}
2020-08-13 22:37:55.729 [error] <0.941.0> CRASH REPORT Process <0.941.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[{ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Puzzlespace.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.Puzzlespace.User',auth_tokens => #{'__cardinality__' => many,'__field__' => auth_tokens,'__owner__' => 'Elixir.Puzzlespace.User','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},...}},...],...},...]},...},...},...}
2020-08-13 22:37:55.731 [error] <0.941.0> Cowboy stream 1 with ranch listener 'Elixir.PuzzlespaceWeb.Endpoint.HTTP' and connection process <0.940.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[{ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Puzzlespace.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.Puzzlespace.User',auth_tokens => #{'__cardinality__' => many,'__field__' => auth_tokens,'__owner__' => 'Elixir.Puzzlespace.User','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},...}},...],...},...]},...},...}
2020-08-13 22:38:10.166 [error] <0.944.0> CRASH REPORT Process <0.944.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[{ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Puzzlespace.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.Puzzlespace.User',auth_tokens => #{'__cardinality__' => many,'__field__' => auth_tokens,'__owner__' => 'Elixir.Puzzlespace.User','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},...}},...],...},...]},...},...},...}
2020-08-13 22:38:10.168 [error] <0.944.0> Cowboy stream 1 with ranch listener 'Elixir.PuzzlespaceWeb.Endpoint.HTTP' and connection process <0.943.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[{ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Puzzlespace.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.Puzzlespace.User',auth_tokens => #{'__cardinality__' => many,'__field__' => auth_tokens,'__owner__' => 'Elixir.Puzzlespace.User','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},...}},...],...},...]},...},...}
2020-08-13 22:38:31.847 [error] <0.947.0> CRASH REPORT Process <0.947.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[{ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Puzzlespace.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.Puzzlespace.User',auth_tokens => #{'__cardinality__' => many,'__field__' => auth_tokens,'__owner__' => 'Elixir.Puzzlespace.User','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},...}},...],...},...]},...},...},...}
2020-08-13 22:38:31.850 [error] <0.947.0> Cowboy stream 1 with ranch listener 'Elixir.PuzzlespaceWeb.Endpoint.HTTP' and connection process <0.946.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[{ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Puzzlespace.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.Puzzlespace.User',auth_tokens => #{'__cardinality__' => many,'__field__' => auth_tokens,'__owner__' => 'Elixir.Puzzlespace.User','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},...}},...],...},...]},...},...}
2020-08-13 22:39:04.290 [error] <0.950.0> CRASH REPORT Process <0.950.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[{ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Puzzlespace.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.Puzzlespace.User',auth_tokens => #{'__cardinality__' => many,'__field__' => auth_tokens,'__owner__' => 'Elixir.Puzzlespace.User','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},...}},...],...},...]},...},...},...}
2020-08-13 22:39:04.291 [error] <0.950.0> Cowboy stream 1 with ranch listener 'Elixir.PuzzlespaceWeb.Endpoint.HTTP' and connection process <0.949.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[{ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Puzzlespace.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.Puzzlespace.User',auth_tokens => #{'__cardinality__' => many,'__field__' => auth_tokens,'__owner__' => 'Elixir.Puzzlespace.User','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},...}},...],...},...]},...},...}
2020-08-13 22:39:52.916 [error] <0.954.0> CRASH REPORT Process <0.954.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[{ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Puzzlespace.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.Puzzlespace.User',auth_tokens => #{'__cardinality__' => many,'__field__' => auth_tokens,'__owner__' => 'Elixir.Puzzlespace.User','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},...}},...],...},...]},...},...},...}
2020-08-13 22:39:52.916 [error] <0.954.0> Cowboy stream 1 with ranch listener 'Elixir.PuzzlespaceWeb.Endpoint.HTTP' and connection process <0.953.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[{ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Puzzlespace.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.Puzzlespace.User',auth_tokens => #{'__cardinality__' => many,'__field__' => auth_tokens,'__owner__' => 'Elixir.Puzzlespace.User','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},...}},...],...},...]},...},...}
2020-08-13 22:40:52.961 [error] <0.957.0> CRASH REPORT Process <0.957.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[{ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Puzzlespace.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.Puzzlespace.User',auth_tokens => #{'__cardinality__' => many,'__field__' => auth_tokens,'__owner__' => 'Elixir.Puzzlespace.User','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},...}},...],...},...]},...},...},...}
2020-08-13 22:40:52.963 [error] <0.957.0> Cowboy stream 1 with ranch listener 'Elixir.PuzzlespaceWeb.Endpoint.HTTP' and connection process <0.956.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[{ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Puzzlespace.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.Puzzlespace.User',auth_tokens => #{'__cardinality__' => many,'__field__' => auth_tokens,'__owner__' => 'Elixir.Puzzlespace.User','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},...}},...],...},...]},...},...}
2020-08-13 22:41:52.998 [error] <0.961.0> CRASH REPORT Process <0.961.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[{ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Puzzlespace.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.Puzzlespace.User',auth_tokens => #{'__cardinality__' => many,'__field__' => auth_tokens,'__owner__' => 'Elixir.Puzzlespace.User','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},...}},...],...},...]},...},...},...}
2020-08-13 22:41:53.000 [error] <0.961.0> Cowboy stream 1 with ranch listener 'Elixir.PuzzlespaceWeb.Endpoint.HTTP' and connection process <0.960.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[{ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Puzzlespace.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.Puzzlespace.User',auth_tokens => #{'__cardinality__' => many,'__field__' => auth_tokens,'__owner__' => 'Elixir.Puzzlespace.User','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},...}},...],...},...]},...},...}
2020-08-13 22:42:53.038 [error] <0.964.0> CRASH REPORT Process <0.964.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[{ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Puzzlespace.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.Puzzlespace.User',auth_tokens => #{'__cardinality__' => many,'__field__' => auth_tokens,'__owner__' => 'Elixir.Puzzlespace.User','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},...}},...],...},...]},...},...},...}
2020-08-13 22:42:53.039 [error] <0.964.0> Cowboy stream 1 with ranch listener 'Elixir.PuzzlespaceWeb.Endpoint.HTTP' and connection process <0.963.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[{ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Puzzlespace.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.Puzzlespace.User',auth_tokens => #{'__cardinality__' => many,'__field__' => auth_tokens,'__owner__' => 'Elixir.Puzzlespace.User','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},...}},...],...},...]},...},...}
2020-08-13 22:43:53.085 [error] <0.968.0> CRASH REPORT Process <0.968.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[{ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Puzzlespace.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.Puzzlespace.User',auth_tokens => #{'__cardinality__' => many,'__field__' => auth_tokens,'__owner__' => 'Elixir.Puzzlespace.User','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},...}},...],...},...]},...},...},...}
2020-08-13 22:43:53.086 [error] <0.968.0> Cowboy stream 1 with ranch listener 'Elixir.PuzzlespaceWeb.Endpoint.HTTP' and connection process <0.967.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[{ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Puzzlespace.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.Puzzlespace.User',auth_tokens => #{'__cardinality__' => many,'__field__' => auth_tokens,'__owner__' => 'Elixir.Puzzlespace.User','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},...}},...],...},...]},...},...}
2020-08-13 22:44:53.130 [error] <0.971.0> CRASH REPORT Process <0.971.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[{ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Puzzlespace.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.Puzzlespace.User',auth_tokens => #{'__cardinality__' => many,'__field__' => auth_tokens,'__owner__' => 'Elixir.Puzzlespace.User','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},...}},...],...},...]},...},...},...}
2020-08-13 22:44:53.130 [error] <0.971.0> Cowboy stream 1 with ranch listener 'Elixir.PuzzlespaceWeb.Endpoint.HTTP' and connection process <0.970.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[{ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Puzzlespace.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.Puzzlespace.User',auth_tokens => #{'__cardinality__' => many,'__field__' => auth_tokens,'__owner__' => 'Elixir.Puzzlespace.User','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},...}},...],...},...]},...},...}
2020-08-13 22:45:53.385 [error] <0.975.0> CRASH REPORT Process <0.975.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => <<"511e73b2-a787-4ab3-8c14-623c76a10dab">>},[{'Elixir.PuzzlespaceWeb.PuzzleSocket',connect,3,[{file,"lib/puzzlespace_web/channels/puzzle_socket.ex"},{line,20}]},{'Elixir.Phoenix.Socket',user_connect,4,[{file,"lib/phoenix/socket.ex"},{line,572}]},{'Elixir.Phoenix.Socket','__connect__',3,[{file,"lib/phoenix/socket.ex"},{line,434}]},{'Elixir.Phoenix.Transports.WebSocket',connect,4,[{file,"lib/phoenix/transports/w..."},...]},...]},...},...},...}
2020-08-13 22:45:53.387 [error] <0.975.0> Cowboy stream 1 with ranch listener 'Elixir.PuzzlespaceWeb.Endpoint.HTTP' and connection process <0.974.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => <<"511e73b2-a787-4ab3-8c14-623c76a10dab">>},[{'Elixir.PuzzlespaceWeb.PuzzleSocket',connect,3,[{file,"lib/puzzlespace_web/channels/puzzle_socket.ex"},{line,20}]},{'Elixir.Phoenix.Socket',user_connect,4,[{file,"lib/phoenix/socket.ex"},{line,572}]},{'Elixir.Phoenix.Socket','__connect__',3,[{file,"lib/phoenix/socket.ex"},{line,434}]},{'Elixir.Phoenix.Transports.WebSocket',connect,4,[{file,"lib/phoenix/transports/web..."},...]},...]},...},...}
2020-08-13 22:47:12.034 [error] <0.879.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:join:8 gen_server <0.879.0> terminated with reason: bad argument in call to erlang:apply({ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,...},...}}, owner, []) in 'Elixir.PuzzlespaceWeb.STPuzzChannel':join/3 line 8
2020-08-13 22:47:12.098 [error] <0.879.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:join:8 CRASH REPORT Process <0.879.0> with 0 neighbours crashed with reason: bad argument in call to erlang:apply({ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,...},...}}, owner, []) in 'Elixir.PuzzlespaceWeb.STPuzzChannel':join/3 line 8
2020-08-13 22:47:12.098 [error] <0.477.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:join:8 Supervisor {<0.477.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.PuzzlespaceWeb.STPuzzChannel',start_link,undefined} at <0.879.0> exit with reason bad argument in call to erlang:apply({ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,...},...}}, owner, []) in 'Elixir.PuzzlespaceWeb.STPuzzChannel':join/3 line 8 in context child_terminated
2020-08-13 22:47:12.108 [error] <0.883.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:join:8 gen_server <0.883.0> terminated with reason: bad argument in call to erlang:apply({ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,...},...}}, owner, []) in 'Elixir.PuzzlespaceWeb.STPuzzChannel':join/3 line 8
2020-08-13 22:47:12.110 [error] <0.883.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:join:8 CRASH REPORT Process <0.883.0> with 0 neighbours crashed with reason: bad argument in call to erlang:apply({ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,...},...}}, owner, []) in 'Elixir.PuzzlespaceWeb.STPuzzChannel':join/3 line 8
2020-08-13 22:47:12.110 [error] <0.477.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:join:8 Supervisor {<0.477.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.PuzzlespaceWeb.STPuzzChannel',start_link,undefined} at <0.883.0> exit with reason bad argument in call to erlang:apply({ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,...},...}}, owner, []) in 'Elixir.PuzzlespaceWeb.STPuzzChannel':join/3 line 8 in context child_terminated
2020-08-13 22:47:13.142 [error] <0.886.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:join:8 gen_server <0.886.0> terminated with reason: bad argument in call to erlang:apply({ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,...},...}}, owner, []) in 'Elixir.PuzzlespaceWeb.STPuzzChannel':join/3 line 8
2020-08-13 22:47:13.143 [error] <0.886.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:join:8 CRASH REPORT Process <0.886.0> with 0 neighbours crashed with reason: bad argument in call to erlang:apply({ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,...},...}}, owner, []) in 'Elixir.PuzzlespaceWeb.STPuzzChannel':join/3 line 8
2020-08-13 22:47:13.144 [error] <0.478.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:join:8 Supervisor {<0.478.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.PuzzlespaceWeb.STPuzzChannel',start_link,undefined} at <0.886.0> exit with reason bad argument in call to erlang:apply({ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,...},...}}, owner, []) in 'Elixir.PuzzlespaceWeb.STPuzzChannel':join/3 line 8 in context child_terminated
2020-08-13 22:47:15.156 [error] <0.887.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:join:8 gen_server <0.887.0> terminated with reason: bad argument in call to erlang:apply({ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,...},...}}, owner, []) in 'Elixir.PuzzlespaceWeb.STPuzzChannel':join/3 line 8
2020-08-13 22:47:15.159 [error] <0.887.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:join:8 CRASH REPORT Process <0.887.0> with 0 neighbours crashed with reason: bad argument in call to erlang:apply({ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,...},...}}, owner, []) in 'Elixir.PuzzlespaceWeb.STPuzzChannel':join/3 line 8
2020-08-13 22:47:15.159 [error] <0.480.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:join:8 Supervisor {<0.480.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.PuzzlespaceWeb.STPuzzChannel',start_link,undefined} at <0.887.0> exit with reason bad argument in call to erlang:apply({ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,...},...}}, owner, []) in 'Elixir.PuzzlespaceWeb.STPuzzChannel':join/3 line 8 in context child_terminated
2020-08-13 22:47:20.166 [error] <0.888.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:join:8 gen_server <0.888.0> terminated with reason: bad argument in call to erlang:apply({ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,...},...}}, owner, []) in 'Elixir.PuzzlespaceWeb.STPuzzChannel':join/3 line 8
2020-08-13 22:47:20.167 [error] <0.888.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:join:8 CRASH REPORT Process <0.888.0> with 0 neighbours crashed with reason: bad argument in call to erlang:apply({ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,...},...}}, owner, []) in 'Elixir.PuzzlespaceWeb.STPuzzChannel':join/3 line 8
2020-08-13 22:47:20.167 [error] <0.479.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:join:8 Supervisor {<0.479.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.PuzzlespaceWeb.STPuzzChannel',start_link,undefined} at <0.888.0> exit with reason bad argument in call to erlang:apply({ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,...},...}}, owner, []) in 'Elixir.PuzzlespaceWeb.STPuzzChannel':join/3 line 8 in context child_terminated
2020-08-13 22:47:30.174 [error] <0.889.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:join:8 gen_server <0.889.0> terminated with reason: bad argument in call to erlang:apply({ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,...},...}}, owner, []) in 'Elixir.PuzzlespaceWeb.STPuzzChannel':join/3 line 8
2020-08-13 22:47:30.177 [error] <0.889.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:join:8 CRASH REPORT Process <0.889.0> with 0 neighbours crashed with reason: bad argument in call to erlang:apply({ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,...},...}}, owner, []) in 'Elixir.PuzzlespaceWeb.STPuzzChannel':join/3 line 8
2020-08-13 22:47:30.177 [error] <0.479.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:join:8 Supervisor {<0.479.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.PuzzlespaceWeb.STPuzzChannel',start_link,undefined} at <0.889.0> exit with reason bad argument in call to erlang:apply({ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,...},...}}, owner, []) in 'Elixir.PuzzlespaceWeb.STPuzzChannel':join/3 line 8 in context child_terminated
2020-08-13 22:47:40.185 [error] <0.890.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:join:8 gen_server <0.890.0> terminated with reason: bad argument in call to erlang:apply({ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,...},...}}, owner, []) in 'Elixir.PuzzlespaceWeb.STPuzzChannel':join/3 line 8
2020-08-13 22:47:40.187 [error] <0.890.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:join:8 CRASH REPORT Process <0.890.0> with 0 neighbours crashed with reason: bad argument in call to erlang:apply({ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,...},...}}, owner, []) in 'Elixir.PuzzlespaceWeb.STPuzzChannel':join/3 line 8
2020-08-13 22:47:40.187 [error] <0.478.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:join:8 Supervisor {<0.478.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.PuzzlespaceWeb.STPuzzChannel',start_link,undefined} at <0.890.0> exit with reason bad argument in call to erlang:apply({ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,...},...}}, owner, []) in 'Elixir.PuzzlespaceWeb.STPuzzChannel':join/3 line 8 in context child_terminated
2020-08-13 22:47:50.196 [error] <0.891.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:join:8 gen_server <0.891.0> terminated with reason: bad argument in call to erlang:apply({ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,...},...}}, owner, []) in 'Elixir.PuzzlespaceWeb.STPuzzChannel':join/3 line 8
2020-08-13 22:47:50.198 [error] <0.891.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:join:8 CRASH REPORT Process <0.891.0> with 0 neighbours crashed with reason: bad argument in call to erlang:apply({ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,...},...}}, owner, []) in 'Elixir.PuzzlespaceWeb.STPuzzChannel':join/3 line 8
2020-08-13 22:47:50.198 [error] <0.477.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:join:8 Supervisor {<0.477.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.PuzzlespaceWeb.STPuzzChannel',start_link,undefined} at <0.891.0> exit with reason bad argument in call to erlang:apply({ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,...},...}}, owner, []) in 'Elixir.PuzzlespaceWeb.STPuzzChannel':join/3 line 8 in context child_terminated
2020-08-13 22:48:00.203 [error] <0.892.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:join:8 gen_server <0.892.0> terminated with reason: bad argument in call to erlang:apply({ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,...},...}}, owner, []) in 'Elixir.PuzzlespaceWeb.STPuzzChannel':join/3 line 8
2020-08-13 22:48:00.205 [error] <0.892.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:join:8 CRASH REPORT Process <0.892.0> with 0 neighbours crashed with reason: bad argument in call to erlang:apply({ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,...},...}}, owner, []) in 'Elixir.PuzzlespaceWeb.STPuzzChannel':join/3 line 8
2020-08-13 22:48:00.206 [error] <0.478.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:join:8 Supervisor {<0.478.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.PuzzlespaceWeb.STPuzzChannel',start_link,undefined} at <0.892.0> exit with reason bad argument in call to erlang:apply({ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,...},...}}, owner, []) in 'Elixir.PuzzlespaceWeb.STPuzzChannel':join/3 line 8 in context child_terminated
2020-08-13 22:48:10.212 [error] <0.893.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:join:8 gen_server <0.893.0> terminated with reason: bad argument in call to erlang:apply({ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,...},...}}, owner, []) in 'Elixir.PuzzlespaceWeb.STPuzzChannel':join/3 line 8
2020-08-13 22:48:10.215 [error] <0.893.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:join:8 CRASH REPORT Process <0.893.0> with 0 neighbours crashed with reason: bad argument in call to erlang:apply({ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,...},...}}, owner, []) in 'Elixir.PuzzlespaceWeb.STPuzzChannel':join/3 line 8
2020-08-13 22:48:10.215 [error] <0.478.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:join:8 Supervisor {<0.478.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.PuzzlespaceWeb.STPuzzChannel',start_link,undefined} at <0.893.0> exit with reason bad argument in call to erlang:apply({ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,...},...}}, owner, []) in 'Elixir.PuzzlespaceWeb.STPuzzChannel':join/3 line 8 in context child_terminated
2020-08-13 22:48:20.223 [error] <0.895.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:join:8 gen_server <0.895.0> terminated with reason: bad argument in call to erlang:apply({ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,...},...}}, owner, []) in 'Elixir.PuzzlespaceWeb.STPuzzChannel':join/3 line 8
2020-08-13 22:48:20.226 [error] <0.895.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:join:8 CRASH REPORT Process <0.895.0> with 0 neighbours crashed with reason: bad argument in call to erlang:apply({ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,...},...}}, owner, []) in 'Elixir.PuzzlespaceWeb.STPuzzChannel':join/3 line 8
2020-08-13 22:48:20.226 [error] <0.480.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:join:8 Supervisor {<0.480.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.PuzzlespaceWeb.STPuzzChannel',start_link,undefined} at <0.895.0> exit with reason bad argument in call to erlang:apply({ok,#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,...},...}}, owner, []) in 'Elixir.PuzzlespaceWeb.STPuzzChannel':join/3 line 8 in context child_terminated
2020-08-13 22:48:42.321 [error] <0.887.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:join:8 gen_server <0.887.0> terminated with reason: no case clause matching granted in 'Elixir.PuzzlespaceWeb.STPuzzChannel':join/3 line 8
2020-08-13 22:48:42.452 [error] <0.887.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:join:8 CRASH REPORT Process <0.887.0> with 0 neighbours crashed with reason: no case clause matching granted in 'Elixir.PuzzlespaceWeb.STPuzzChannel':join/3 line 8
2020-08-13 22:48:42.452 [error] <0.470.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:join:8 Supervisor {<0.470.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.PuzzlespaceWeb.STPuzzChannel',start_link,undefined} at <0.887.0> exit with reason no case clause matching granted in 'Elixir.PuzzlespaceWeb.STPuzzChannel':join/3 line 8 in context child_terminated
2020-08-13 22:48:43.462 [error] <0.889.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:join:8 gen_server <0.889.0> terminated with reason: no case clause matching granted in 'Elixir.PuzzlespaceWeb.STPuzzChannel':join/3 line 8
2020-08-13 22:48:43.466 [error] <0.889.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:join:8 CRASH REPORT Process <0.889.0> with 0 neighbours crashed with reason: no case clause matching granted in 'Elixir.PuzzlespaceWeb.STPuzzChannel':join/3 line 8
2020-08-13 22:48:43.466 [error] <0.467.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:join:8 Supervisor {<0.467.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.PuzzlespaceWeb.STPuzzChannel',start_link,undefined} at <0.889.0> exit with reason no case clause matching granted in 'Elixir.PuzzlespaceWeb.STPuzzChannel':join/3 line 8 in context child_terminated
2020-08-13 22:48:45.470 [error] <0.890.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:join:8 gen_server <0.890.0> terminated with reason: no case clause matching granted in 'Elixir.PuzzlespaceWeb.STPuzzChannel':join/3 line 8
2020-08-13 22:48:45.472 [error] <0.890.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:join:8 CRASH REPORT Process <0.890.0> with 0 neighbours crashed with reason: no case clause matching granted in 'Elixir.PuzzlespaceWeb.STPuzzChannel':join/3 line 8
2020-08-13 22:48:45.472 [error] <0.468.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:join:8 Supervisor {<0.468.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.PuzzlespaceWeb.STPuzzChannel',start_link,undefined} at <0.890.0> exit with reason no case clause matching granted in 'Elixir.PuzzlespaceWeb.STPuzzChannel':join/3 line 8 in context child_terminated
2020-08-13 22:48:50.479 [error] <0.891.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:join:8 gen_server <0.891.0> terminated with reason: no case clause matching granted in 'Elixir.PuzzlespaceWeb.STPuzzChannel':join/3 line 8
2020-08-13 22:48:50.481 [error] <0.891.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:join:8 CRASH REPORT Process <0.891.0> with 0 neighbours crashed with reason: no case clause matching granted in 'Elixir.PuzzlespaceWeb.STPuzzChannel':join/3 line 8
2020-08-13 22:48:50.481 [error] <0.468.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:join:8 Supervisor {<0.468.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.PuzzlespaceWeb.STPuzzChannel',start_link,undefined} at <0.891.0> exit with reason no case clause matching granted in 'Elixir.PuzzlespaceWeb.STPuzzChannel':join/3 line 8 in context child_terminated
2020-08-13 23:43:31.624 [error] <0.897.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:handle_in:15 gen_server <0.897.0> terminated with reason: no function clause matching 'Elixir.PuzzlespaceWeb.STPuzzChannel':handle_in(<<"user_input">>, #{<<"body">> => <<"{\"user_input\":[{\"pos_x\":129,\"pos_y\":65,\"buttons\":[\"M1\"],\"mouse\":\"DOWN\"},{\"pos_...">>}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{slotid => <<"dc024500-d8b2-482d-a4a4-460c...">>,...},...}) line 15
2020-08-13 23:43:31.659 [error] <0.897.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:handle_in:15 CRASH REPORT Process <0.897.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.PuzzlespaceWeb.STPuzzChannel':handle_in(<<"user_input">>, #{<<"body">> => <<"{\"user_input\":[{\"pos_x\":129,\"pos_y\":65,\"buttons\":[\"M1\"],\"mouse\":\"DOWN\"},{\"pos_...">>}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{slotid => <<"dc024500-d8b2-482d-a4a4-460c...">>,...},...}) line 15
2020-08-13 23:43:31.659 [error] <0.486.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:handle_in:15 Supervisor {<0.486.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.PuzzlespaceWeb.STPuzzChannel',start_link,undefined} at <0.897.0> exit with reason no function clause matching 'Elixir.PuzzlespaceWeb.STPuzzChannel':handle_in(<<"user_input">>, #{<<"body">> => <<"{\"user_input\":[{\"pos_x\":129,\"pos_y\":65,\"buttons\":[\"M1\"],\"mouse\":\"DOWN\"},{\"pos_...">>}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{slotid => <<"dc024500-d8b2-482d-a4a4-460c...">>,...},...}) line 15 in context child_terminated
2020-08-13 23:43:45.814 [error] <0.899.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:handle_in:15 gen_server <0.899.0> terminated with reason: no function clause matching 'Elixir.PuzzlespaceWeb.STPuzzChannel':handle_in(<<"user_input">>, #{<<"body">> => <<"{\"user_input\":[{\"pos_x\":133,\"pos_y\":63,\"buttons\":[\"M1\"],\"mouse\":\"DOWN\"},{\"pos_...">>}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{slotid => <<"dc024500-d8b2-482d-a4a4-460c...">>,...},...}) line 15
2020-08-13 23:43:45.817 [error] <0.899.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:handle_in:15 CRASH REPORT Process <0.899.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.PuzzlespaceWeb.STPuzzChannel':handle_in(<<"user_input">>, #{<<"body">> => <<"{\"user_input\":[{\"pos_x\":133,\"pos_y\":63,\"buttons\":[\"M1\"],\"mouse\":\"DOWN\"},{\"pos_...">>}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{slotid => <<"dc024500-d8b2-482d-a4a4-460c...">>,...},...}) line 15
2020-08-13 23:43:45.817 [error] <0.483.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:handle_in:15 Supervisor {<0.483.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.PuzzlespaceWeb.STPuzzChannel',start_link,undefined} at <0.899.0> exit with reason no function clause matching 'Elixir.PuzzlespaceWeb.STPuzzChannel':handle_in(<<"user_input">>, #{<<"body">> => <<"{\"user_input\":[{\"pos_x\":133,\"pos_y\":63,\"buttons\":[\"M1\"],\"mouse\":\"DOWN\"},{\"pos_...">>}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{slotid => <<"dc024500-d8b2-482d-a4a4-460c...">>,...},...}) line 15 in context child_terminated
2020-08-13 23:43:54.488 [error] <0.900.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:handle_in:15 gen_server <0.900.0> terminated with reason: no function clause matching 'Elixir.PuzzlespaceWeb.STPuzzChannel':handle_in(<<"user_input">>, #{<<"body">> => <<"{\"user_input\":[{\"pos_x\":178,\"pos_y\":60,\"buttons\":[\"M1\"],\"mouse\":\"DOWN\"},{\"pos_...">>}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{slotid => <<"dc024500-d8b2-482d-a4a4-460c...">>,...},...}) line 15
2020-08-13 23:43:54.490 [error] <0.900.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:handle_in:15 CRASH REPORT Process <0.900.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.PuzzlespaceWeb.STPuzzChannel':handle_in(<<"user_input">>, #{<<"body">> => <<"{\"user_input\":[{\"pos_x\":178,\"pos_y\":60,\"buttons\":[\"M1\"],\"mouse\":\"DOWN\"},{\"pos_...">>}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{slotid => <<"dc024500-d8b2-482d-a4a4-460c...">>,...},...}) line 15
2020-08-13 23:43:54.491 [error] <0.483.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:handle_in:15 Supervisor {<0.483.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.PuzzlespaceWeb.STPuzzChannel',start_link,undefined} at <0.900.0> exit with reason no function clause matching 'Elixir.PuzzlespaceWeb.STPuzzChannel':handle_in(<<"user_input">>, #{<<"body">> => <<"{\"user_input\":[{\"pos_x\":178,\"pos_y\":60,\"buttons\":[\"M1\"],\"mouse\":\"DOWN\"},{\"pos_...">>}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{slotid => <<"dc024500-d8b2-482d-a4a4-460c...">>,...},...}) line 15 in context child_terminated
2020-08-13 23:44:07.143 [error] <0.901.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:handle_in:15 gen_server <0.901.0> terminated with reason: no function clause matching 'Elixir.PuzzlespaceWeb.STPuzzChannel':handle_in(<<"user_input">>, #{<<"body">> => <<"{\"user_input\":[{\"pos_x\":56,\"pos_y\":187,\"buttons\":[\"M1\"],\"mouse\":\"DOWN\"},{\"pos_...">>}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{slotid => <<"dc024500-d8b2-482d-a4a4-460c...">>,...},...}) line 15
2020-08-13 23:44:07.145 [error] <0.901.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:handle_in:15 CRASH REPORT Process <0.901.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.PuzzlespaceWeb.STPuzzChannel':handle_in(<<"user_input">>, #{<<"body">> => <<"{\"user_input\":[{\"pos_x\":56,\"pos_y\":187,\"buttons\":[\"M1\"],\"mouse\":\"DOWN\"},{\"pos_...">>}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{slotid => <<"dc024500-d8b2-482d-a4a4-460c...">>,...},...}) line 15
2020-08-13 23:44:07.146 [error] <0.483.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:handle_in:15 Supervisor {<0.483.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.PuzzlespaceWeb.STPuzzChannel',start_link,undefined} at <0.901.0> exit with reason no function clause matching 'Elixir.PuzzlespaceWeb.STPuzzChannel':handle_in(<<"user_input">>, #{<<"body">> => <<"{\"user_input\":[{\"pos_x\":56,\"pos_y\":187,\"buttons\":[\"M1\"],\"mouse\":\"DOWN\"},{\"pos_...">>}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{slotid => <<"dc024500-d8b2-482d-a4a4-460c...">>,...},...}) line 15 in context child_terminated
2020-08-13 23:44:13.936 [error] <0.902.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:handle_in:15 gen_server <0.902.0> terminated with reason: no function clause matching 'Elixir.PuzzlespaceWeb.STPuzzChannel':handle_in(<<"user_input">>, #{<<"body">> => <<"{\"user_input\":[{\"pos_x\":189,\"pos_y\":131,\"buttons\":[\"M1\"],\"mouse\":\"DOWN\"},{\"pos...">>}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{slotid => <<"dc024500-d8b2-482d-a4a4-460c...">>,...},...}) line 15
2020-08-13 23:44:13.938 [error] <0.902.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:handle_in:15 CRASH REPORT Process <0.902.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.PuzzlespaceWeb.STPuzzChannel':handle_in(<<"user_input">>, #{<<"body">> => <<"{\"user_input\":[{\"pos_x\":189,\"pos_y\":131,\"buttons\":[\"M1\"],\"mouse\":\"DOWN\"},{\"pos...">>}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{slotid => <<"dc024500-d8b2-482d-a4a4-460c...">>,...},...}) line 15
2020-08-13 23:44:13.939 [error] <0.485.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:handle_in:15 Supervisor {<0.485.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.PuzzlespaceWeb.STPuzzChannel',start_link,undefined} at <0.902.0> exit with reason no function clause matching 'Elixir.PuzzlespaceWeb.STPuzzChannel':handle_in(<<"user_input">>, #{<<"body">> => <<"{\"user_input\":[{\"pos_x\":189,\"pos_y\":131,\"buttons\":[\"M1\"],\"mouse\":\"DOWN\"},{\"pos...">>}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{slotid => <<"dc024500-d8b2-482d-a4a4-460c...">>,...},...}) line 15 in context child_terminated
2020-08-13 23:46:45.974 [error] <0.606.0> gen_server <0.606.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"unknown registry: Puzzlespace.PubSub">>} in 'Elixir.Registry':'info!'/1 line 1239
2020-08-13 23:46:46.710 [error] <0.606.0> CRASH REPORT Process <0.606.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"unknown registry: Puzzlespace.PubSub">>} in 'Elixir.Registry':'info!'/1 line 1239
2020-08-13 23:46:46.715 [error] <0.473.0> Supervisor {<0.473.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveReloader.Channel',start_link,undefined} at <0.606.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"unknown registry: Puzzlespace.PubSub">>} in 'Elixir.Registry':'info!'/1 line 1239 in context child_terminated
2020-08-13 23:46:46.791 [error] <0.601.0> CRASH REPORT Process <0.601.0> with 0 neighbours exited with reason: {{{{noproc,{'Elixir.GenServer',call,['Elixir.Puzzlespace.SessionHandler',{check,<<"P4/gEGDI4sasxQvwqw8wSxg9+I0=">>},5000]}},{'Elixir.PuzzlespaceWeb.Endpoint',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"en-US,en;q=0.5">>,<<"cache-control">> => <<"no-cache">>,<<"connect...">> => ...,...},...}},...},...]}},...},...}
2020-08-13 23:46:46.831 [error] <0.601.0> Cowboy stream 1 with ranch listener 'Elixir.PuzzlespaceWeb.Endpoint.HTTP' and connection process <0.600.0> had its request process exit with reason: {{{noproc,{'Elixir.GenServer',call,['Elixir.Puzzlespace.SessionHandler',{check,<<"P4/gEGDI4sasxQvwqw8wSxg9+I0=">>},5000]}},{'Elixir.PuzzlespaceWeb.Endpoint',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"en-US,en;q=0.5">>,<<"cache-control">> => <<"no-cache">>,<<"connectio...">> => ...,...},...}},...},...]}},...}
2020-08-13 23:46:57.438 [error] <0.919.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:handle_in:15 gen_server <0.919.0> terminated with reason: no function clause matching 'Elixir.PuzzlespaceWeb.STPuzzChannel':handle_in(<<"user_input">>, #{<<"body">> => <<"{\"user_input\":[{\"pos_x\":200,\"pos_y\":135,\"buttons\":[\"M1\"],\"mouse\":\"DOWN\"},{\"pos...">>}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{slotid => <<"dc024500-d8b2-482d-a4a4-460c...">>,...},...}) line 15
2020-08-13 23:46:57.463 [error] <0.919.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:handle_in:15 CRASH REPORT Process <0.919.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.PuzzlespaceWeb.STPuzzChannel':handle_in(<<"user_input">>, #{<<"body">> => <<"{\"user_input\":[{\"pos_x\":200,\"pos_y\":135,\"buttons\":[\"M1\"],\"mouse\":\"DOWN\"},{\"pos...">>}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{slotid => <<"dc024500-d8b2-482d-a4a4-460c...">>,...},...}) line 15
2020-08-13 23:46:57.464 [error] <0.479.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:handle_in:15 Supervisor {<0.479.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.PuzzlespaceWeb.STPuzzChannel',start_link,undefined} at <0.919.0> exit with reason no function clause matching 'Elixir.PuzzlespaceWeb.STPuzzChannel':handle_in(<<"user_input">>, #{<<"body">> => <<"{\"user_input\":[{\"pos_x\":200,\"pos_y\":135,\"buttons\":[\"M1\"],\"mouse\":\"DOWN\"},{\"pos...">>}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{slotid => <<"dc024500-d8b2-482d-a4a4-460c...">>,...},...}) line 15 in context child_terminated
2020-08-13 23:48:11.736 [error] <0.924.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:handle_in:15 gen_server <0.924.0> terminated with reason: no function clause matching 'Elixir.PuzzlespaceWeb.STPuzzChannel':handle_in(<<"user_input">>, #{<<"body">> => <<"{\"user_input\":[{\"pos_x\":196,\"pos_y\":126,\"buttons\":[\"M1\"],\"mouse\":\"DOWN\"},{\"pos...">>}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{slotid => <<"dc024500-d8b2-482d-a4a4-460c...">>,...},...}) line 15
2020-08-13 23:48:11.738 [error] <0.924.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:handle_in:15 CRASH REPORT Process <0.924.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.PuzzlespaceWeb.STPuzzChannel':handle_in(<<"user_input">>, #{<<"body">> => <<"{\"user_input\":[{\"pos_x\":196,\"pos_y\":126,\"buttons\":[\"M1\"],\"mouse\":\"DOWN\"},{\"pos...">>}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{slotid => <<"dc024500-d8b2-482d-a4a4-460c...">>,...},...}) line 15
2020-08-13 23:48:11.739 [error] <0.478.0>@Elixir.PuzzlespaceWeb.STPuzzChannel:handle_in:15 Supervisor {<0.478.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.PuzzlespaceWeb.STPuzzChannel',start_link,undefined} at <0.924.0> exit with reason no function clause matching 'Elixir.PuzzlespaceWeb.STPuzzChannel':handle_in(<<"user_input">>, #{<<"body">> => <<"{\"user_input\":[{\"pos_x\":196,\"pos_y\":126,\"buttons\":[\"M1\"],\"mouse\":\"DOWN\"},{\"pos...">>}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{slotid => <<"dc024500-d8b2-482d-a4a4-460c...">>,...},...}) line 15 in context child_terminated
